### ISSUE TITLE
market board support

### ISSUE THREAD

**Issue by ttilley** [sruon/ffxivlib#1]
Hello! I need a little help figuring out how to pull data from the market board and log it for later analysis. Quote from last night's exploration:

> next market memory scraping attempt:
> 
> wand of flames, prices:
> 2,000
> 2,500
> 2,500
> 
> found the 2000 at 11B3A198
> found the 2500 at 11B3A1AC
> found the 2500 at 11B3A1C0
> 
> after each price block of 4 bytes (i was apparently wrong with the 8 byte guess earlier?):
> 01 00 00 00 00 00 00 00 D1 ED 00 00 00 00 00 00
> 
> the memory at 11B3A194 appears to contain the number of prices in the list.
> 
> ...going to try to see what those further bytes mean after the price.
> 
> now... this is slightly confusing, but there appears to be a mirror of this structure with the first price also appearing at location 1140B830?
> 
> EDIT: further investigation
> 
> in blocks of 4 bytes, the purpose appears to be: price, quantity, HQ, unknown, materia slots filled
> 
> I REALLY wish i knew what that unknown field was for. in limited debugging it appears to only have 3 values across all of the items i've looked up.

Of course, these memory locations change on each fresh launch of FFXIV and I have no idea how to find concrete anchors for that range (pointers+offsets such as you already use). Any help in figuring this out would be GREATLY appreciated.

The goal is to automate scraping the marketplace's current items up for sale (and at some point in the future, the history as well) for later analysis. Stuff like... What craft can I grind right now and still make gil while grinding, or what is the most optimum use of my gathering/mining time due to either shortages or fast-selling items or high-selling items. etc. You get the picture: market economics support code. Kind of like... a Bloomberg reports for FFXIV.

Would you be willing to help me out here? I'm in waaaay over my head. I'm a mac guy who writes web apps in C/Java/Ruby/Python/JavaScript/CoffeeScript/SASS and iOS apps in C/ObjC/JavaScript... I've never written code for windows before in my life (or had to reverse engineer symbol-stripped code on windows).

**Comment by syncsyncsynchalt** [comment]
cool

**Comment by sruon** [comment]
I'll take a look soon, if you have more infos please tell. :)

**Comment by sruon** [comment]
Well I have found pretty much what you said, I've only given it a quick look but there is the number of elements (+4 apparently? 30 for 26 items) in the container and then it's just N structures. Shouldn't be too hard to implement. I'll give it more time tomorrow.

**Comment by ttilley** [comment]
I've found some weird shit. The "number of items" is reliably updated in 4
locations in memory. Two of those update to 0 when the listing is closed,
the other two retain the previous value cached.

There are two locations where item listing data is stored, each somewhat
nearby each of the updates-to-zero numbers. However, this time the entries
are slightly different. The value in the "unknown" field can be different.

Why the hell are there so many copies of that data???

...I can't figure out a stable pointer path. I'm a noob at this. Any assist
would be AWESOME.

My eventual goal is obviously to scrape the auction house data and do
something similar to ffxiah.com. :)

On Friday, November 15, 2013, sruon wrote:

> Well I have found pretty much what you said, I've only given it a quick
> look but there is the number of elements (+4 apparently? 30 for 26 items)
> in the container and then it's just N structures. Shouldn't be too hard to
> implement. I'll give it more time tomorrow.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sruon/ffxivlib/issues/1#issuecomment-28610002
> .

## 

Sent from Gmail Mobile

**Comment by sruon** [comment]
I don't know at the moment, but data is often duplicated because the widgets have their own serialized data sources bound to controls (i.e. the AH window).

I would love a project such as ffxiah for FFXIV but I don't think scraping the memory is the way to go as it is very slow and requires characters in game on every server. 
Speaking directly with the server through forged packets is probably the best option for that.

Anyway I'll take a look.

**Comment by sruon** [comment]
Okay, I have spent a fair bit of time on this today:

The infos are located twice in memory:
- First array holds current browsed category, you can find ItemID found in the current category. Right after this array is an integer indicating how many items there are of the currently browsed item (after clicking on the item), then in the following array is found a limited amount of informations such as price.
- Second array holds current browsed item informations. (That's the one you want)
  Each entry is 60 bytes long and composed of:

```
0x0 SellerID (Need to find how to map it to name, shouldn't be too hard) INT
0x14 Price INT
0x1C Quantity INT
0x24 ItemID (can be mapped to Item.xml) INT
0x26 Durability Short
```

There is probably more information such as Materia, Spiritbond and stuff.

I haven't managed to find a valid pointer path for this but there is a signature that can be used which is 

```
40000000060000000000000000014164646F6E00
```

Process: 
Find address of start of signature
Substract 0x90 and read the address at this position
This will point you almost to the right address then adjust by a few bytes to find the first item.

Let me know what you find.

**Comment by syncsyncsynchalt** [comment]
wooow, kooooooool

**Comment by ttilley** [comment]
ignoring _current_ prices for a second, i **have** found two stable pointer paths for the _historical_ price data (after that data is looked up, anyways).

"ffxiv.exe"+010B6228
+1c0
+20
+af8

"ffxiv.exe"+010B5D2C
+12c
+a0
+20
+af8

**Comment by ttilley** [comment]
that points to the number of historical results. after that 4 byte block starts the price listing. each entry appears to be 24 bytes. That third block of 4 bytes appears to contain the info about whether or not the item is HQ.
