### ISSUE TITLE
GetEntityById doesn't work on FFXIV2.1 JAPANESE client

### ISSUE THREAD

**Issue by xjaoijfoaweijfa** [sruon/ffxivlib#15]
This code doesn't work on japanese client 2.1.
How are other Multi-bytes language?

```
FFXIVLIB ffxiv = new ffxivlib.FFXIVLIB();
Entity tpEnt;
for (int foo = 0; foo < 100; ++foo)
{
    tpEnt = ffxiv.GetEntityById(foo);
    if (tpEnt != null) )
    {
        Console.Write(tpEnt.Name);
    }
}
```

tpEnt is Always null.

And also doesn't work 

```
IEnumerable<Entity> ents = ffxiv.GetEntityByName("ツインタニア");
```

no list returns.

i tried this code

```
Entity ctgt = ffxiv.GetCurrentTarget();
```

then, ctgt.Structure.Name was were garbled.

I checked String bytes[] ,then, it was shift-jis data.
(string encording was UTF-8,but byte data was for shift-jis)

**Comment by sruon** [comment]
Hello,

I heard that from other people as well, I suggest you take a look at chocopon fork which has updated pointers for japanese version.

The pointer in question : https://github.com/chocopon/ffxivlib/commit/6456dce8259ccc2e0d2d832ac8bc0ec4e3feed95#diff-5240e69d58b0dbbae6f08efbe199edcdR184

The fork itself : https://github.com/chocopon/ffxivlib/

**Comment by xjaoijfoaweijfa** [comment]
Thanks!! I will try this.
