### ISSUE TITLE
Chatlog garbage

### ISSUE THREAD

**Issue by gonztok** [sruon/ffxivlib#2]
The chatlog module seems to sometimes collect garbage and misses 1-2 lines. The offsets seem to jump around when this happens. Here is a log of the resulting parse when this happens  http://pastebin.com/M5TZqiCu
On the line 379 you can see the problem

**Comment by sruon** [comment]
Looks like a logic issue, I'll see what I can do.

**Comment by sruon** [comment]
Haven't had time to take a look yet sorry.

**Comment by sonicos** [comment]
looks like it may have choked on the apos in Hawk's Eye. Just kinda cursory glance at the pastebin.

**Comment by sruon** [comment]
I believe it is simply a logic error somewhere on the offsets as you can see it jump to 27555 which causes it to read much more than it is supposed to. Do you have any idea how often this happens?
